apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv1
spec:
  selector:
    matchLabels:
      run: app
      app: echo
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        run: app
        app: echo
        version: v1
    spec:
      containers:
      - name: app-v1
        # imagePullPolicy: Never
        image: local/app:1.0.0
        ports:
        - containerPort: 80