apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2
spec:
  selector:
    matchLabels:
      run: app
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        run: app
        version: v2
    spec:
      containers:
      - name: app-v2
        # imagePullPolicy: Never
        image: local/app:2.0.0
        ports:
        - containerPort: 80