apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      run: app
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app-rolling
        # imagePullPolicy: Never
        image: local/app:1.0.0
        ports:
        - containerPort: 80