apiVersion: v1
kind: Pod
metadata:
  name: appv1
  labels:
    run: appv1
spec:
  containers:
  - name: appv1
    imagePullPolicy: Never
    image: local/appv1
    ports:
    - containerPort: 80
# spec:
#   containers:
#     - name: appv1
#       image: nginx
#       ports:
#         - name: web
#           containerPort: 80
#           protocol: TCP